# Generated by Django 3.0.6 on 2020-05-31 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWAdminCongregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Congregação',
                'verbose_name_plural': 'Congregações',
            },
        ),
        migrations.AddField(
            model_name='jwadminuser',
            name='congregation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.JWAdminCongregation'),
        ),
    ]
