# Generated by Django 3.0.6 on 2020-06-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwadminuser',
            name='congregation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.JWAdminCongregation'),
        ),
    ]
