# Generated by Django 3.0.7 on 2020-09-11 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_jwadminuser_congregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwadminuser',
            name='congregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.JWAdminCongregation'),
        ),
    ]
