# Generated by Django 3.0.6 on 2020-05-31 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200531_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwadminuser',
            name='congregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.JWAdminCongregation'),
        ),
    ]
