# Generated by Django 3.0.6 on 2020-05-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200513_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='map_url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
