# Generated by Django 3.0.6 on 2020-05-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_territory_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoccurrence',
            name='status',
            field=models.CharField(choices=[('N', 'N'), ('I', 'I'), ('F', 'F'), ('C', 'C')], default='F', max_length=1),
        ),
    ]
