# Generated by Django 3.0.6 on 2020-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200518_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoccurrence',
            name='period',
            field=models.CharField(choices=[('M', 'M'), ('A', 'A')], default='M', max_length=1),
        ),
    ]
